version: "3.8"
services:
  blog:
    user: ${UID}:${GID}
    tty: true
    stdin_open: true
    container_name: blog
    build:
      context: .
    ports:
      - 5000:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
