version: "3.8"
services:
  blog:
    tty: true
    stdin_open: true
    container_name: blog
    build:
      context: ./blog/
    ports:
      - 5000:3000
    volumes:
      - ./blog/:/app
      - ./blog/node_modules:/app/node_modules
