version: "3.8"
services:
  client:
    tty: true
    stdin_open: true
    container_name: client
    build:
      context: ./client/
    ports:
      - 5000:3000
    volumes:
      - ./client/:/app
      - /app/node_modules
